import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { CartProvider } from "./CartContext";
import { PaymentProvider } from "./PaymentContext";
import SliderNavbar from "./Components/SliderNavbar";
import ProductBanner from "./ProductBanner/page";

const inter = Inter({ subsets: ["latin"] });

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="font-serif ">
        <SessionProvider session={session}>
          <CartProvider>
            <PaymentProvider>
              <div className="wrapper">
                <div className="lg:hidden"> {/* Show SliderNavbar on small screens */}
                  <SliderNavbar/>
                </div>
                <div className="hidden lg:block"> {/* Show Navbar on large screens */}
                  <Navbar/>
                </div>              
                <div className="mt-10 pt-7 pb-20">{children}</div>
                <div className="">
                <Footer />

                </div>
              </div>
              <Analytics/>
            </PaymentProvider>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
